import sys; sys.path.insert(0,'src')
import httpx, json
from feishu_mcp.auth import get_auth_headers
from feishu_mcp.tools.documents import create_document, _markdown_to_blocks

doc = create_document('Block Debug Doc')
doc_id = doc['document_id']
print('doc_id:', doc_id)

MD = """# MCP Server Feishu Integration Test Report

## Test Overview

This document was auto-generated by **Feishu MCP Server** to verify cloud document module functionality.

## Tests Passed

1. Stage 1: Messaging module ✅
2. Stage 2: Task module ✅

## Code Example

```python
doc = create_document(title="My Document")
```

---

Tests complete 🎉
"""

blocks = _markdown_to_blocks(MD)
print("Block count:", len(blocks))
for i, blk in enumerate(blocks):
    print(f"\n--- Block {i} type={blk['block_type']} ---")
    print(json.dumps(blk, ensure_ascii=False, indent=2))
    
    payload = {'children': [blk], 'index': -1}
    r = httpx.post(
        f'https://open.feishu.cn/open-apis/docx/v1/documents/{doc_id}/blocks/{doc_id}/children',
        headers=get_auth_headers(),
        json=payload
    )
    d = r.json()
    if d.get('code') != 0:
        print(f"FAIL: code={d['code']} msg={d.get('msg')}")
    else:
        print("OK")